# -*- coding: utf-8 -*-
"""chat1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/165GUpZRbZo964P37i9X8A_jBD9MmG4lB
"""



# -*- coding: utf-8 -*-

import nltk
nltk.download('punkt')
nltk.download('wordnet')
import random
import string
import warnings
warnings.filterwarnings('ignore')

f = open("acne3.txt", 'r', errors='ignore')
raw = f.read()
raw = raw.lower()

sent_tokens = nltk.sent_tokenize(raw) #converts to list of scentences
word_tokens = nltk.word_tokenize(raw) #converts to list of words

sentToken = sent_tokens[:4]
#print(sentToken)
wordToken = word_tokens[:4]
#print(wordToken)

#preprocessing
lemmer = nltk.stem.WordNetLemmatizer()

def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]
remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)

def LemNormalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

#Greetings
GREETING_INPUTS = ("hello", "hi", "greetings", "sup", "what's up", "hey")
GREETING_RESPONSES = ["hi", "hey", "nods", "hi there", "hello", "I am glad! you are talking to me"]

def greeting(scentence):

    for word in scentence.split():
        if word.lower() in GREETING_INPUTS:
            return random.choice(GREETING_RESPONSES)

#Vectorizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def response(user_response):
    chatbot_response = ''
    sent_tokens.append(user_response)
    TfidfVec = TfidfVectorizer(tokenizer=LemNormalize, stop_words="english")
    tfidf = TfidfVec.fit_transform(sent_tokens)
    vals = cosine_similarity(tfidf[-1], tfidf)
    idx = vals.argsort()[0][-2]
    flat = vals.flatten()
    flat.sort()
    req_tfidf = flat[-2]
    if(req_tfidf == 0):
        chatbot_response = chatbot_response + "I am sorry! I don't understand you"
        return chatbot_response

    else:
        chatbot_response=chatbot_response+sent_tokens[idx]
        return chatbot_response


if __name__ == "__main__":
    flag = True
    print("Hello, there my name is Virohana. I will answer your queries about skin diseases such as: \n 1.Bullous Disease \n 2.Cellulitis Impetigo \n 3.Eczema \n 4.Exanthems \n 5. Hair Loss-Alopecia \n 6.Herpes HPV \n 7.Light Diseases \n 8.Lupus \n 9.Melanoma Skin Cancer\n 10.Nail Fungus\n 11.Urticaria Hives\n 12. Tinea Ringworm\n 13.Psoriasis \n 14. Warts Molluscum\n 15.Vascular Tumors\n 16.Scabies Lyme Disease\n 17.Vasculitis\n 18. Systemic Disease\n 19.Poison Ivy-Contact Dermatitis\n 20.Seborrheic Keratoses\n 21. Atopic Dermatitis\n 22. Actinic Keratosis\n 23. Acne\n If you want to exit, type Bye!")



    while(flag==True):
        user_response = input()
        user_response = user_response.lower()
        if(user_response!='bye'):
            if user_response == 'thanks' or user_response == 'thank you':
                flag = False
                print("Virohana: You're welcome!")
            else:
                if(greeting(user_response)!=None):
                    print("Virohana:" +greeting(user_response))
                else:
                    print("Virohana:", end='')
                    print(response(user_response))
                    sent_tokens.remove(user_response)
        else:
            flag = False
            print("Virohana: Bye! Have a great time!" )